platform :ios, '10.0'
use_frameworks!

def available_pods
	
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
  
end

app_targets = ['test_Andersen']

app_targets.each do |app_target|
    target app_target do
        available_pods
    end
end

